// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKlYd7Pr3lfkkeZGCTwXnQZL8SRO22zew',
    appId: '1:164538955460:web:9806777ab22f476a85fb91',
    messagingSenderId: '164538955460',
    projectId: 'exercisedb-69ecc',
    authDomain: 'exercisedb-69ecc.firebaseapp.com',
    storageBucket: 'exercisedb-69ecc.appspot.com',
    measurementId: 'G-6CB162HFWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr5_bizrIdvksPTNlodH7zNRsFtS85wNI',
    appId: '1:164538955460:android:846d71c0042b925685fb91',
    messagingSenderId: '164538955460',
    projectId: 'exercisedb-69ecc',
    storageBucket: 'exercisedb-69ecc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlA3iy5D_cedcZy1y1XG8GiRI2KOE8DLg',
    appId: '1:164538955460:ios:cd847403b52b56cd85fb91',
    messagingSenderId: '164538955460',
    projectId: 'exercisedb-69ecc',
    storageBucket: 'exercisedb-69ecc.appspot.com',
    iosBundleId: 'com.example.fitproFree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlA3iy5D_cedcZy1y1XG8GiRI2KOE8DLg',
    appId: '1:164538955460:ios:cd847403b52b56cd85fb91',
    messagingSenderId: '164538955460',
    projectId: 'exercisedb-69ecc',
    storageBucket: 'exercisedb-69ecc.appspot.com',
    iosBundleId: 'com.example.fitproFree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKlYd7Pr3lfkkeZGCTwXnQZL8SRO22zew',
    appId: '1:164538955460:web:f9c7c894ab668dad85fb91',
    messagingSenderId: '164538955460',
    projectId: 'exercisedb-69ecc',
    authDomain: 'exercisedb-69ecc.firebaseapp.com',
    storageBucket: 'exercisedb-69ecc.appspot.com',
    measurementId: 'G-LNGCZL46PN',
  );
}
